### ISSUE TITLE
Error in SelectLayerByAttribute

### ISSUE THREAD

**Issue by RichThomasUniti** [uniti-tim/gis_multi_site#20]
### Background
Was running the "eRate RFP Analysis" tool when the following error occurred in the code that determines what segments are on fiber vs roads,
### Potential Cause
Most likely because I previously had to hardcode the FIBERCABLE layer in as follows
`    selection = "\"FID_FIBERCABLE_UG_OH_for_ND\" <> -1"`
### Potential Solution
FOr now, please help me hardcode it again properly, and for the permanent fix, look to the network dataset itself for what features are existing fiber. That is issue #10, where we need to add a parameter to the network dataset to be used in the Identity_analysis.
### Error received
`Executing: eRateRFP Sites_PolkCo_Schools OppGroup SiteID UF_COs RoutingND C:\Users\rthomas\Documents\ArcGIS\Erate\20180911_Polk\Polk1 true
Start Time: Tue Sep 11 16:54:23 2018
Running script eRateRFP...
**********************************
Single RFP Route
User Facility layer has been provided...
Found 1 user facilities.
Beginning Locate Assets...
- Locate Assets completed successfully
Creating Closest Facility layer...
- Closest Facility layer created successfully
Beginning Backhaul Optimization...
- Backhaul Optimization completed successfully
Cleaning up the routes...
- Routes intersected.
- Overlapping routes erased.
- Completed cleaning routes.
- Duplicate features removed.
Determining New versus Existing routes...
Failed script eRateRFP...

Traceback (most recent call last):
  File "C:\Users\rthomas\Documents\ArcGIS\Multisite_Routing_Tool\gis_multi_site-master_multiple2\eRate_Routing.py", line 288, in <module>
    outputRoute = rfpRoute(rfpGroup)
  File "C:\Users\rthomas\Documents\ArcGIS\Multisite_Routing_Tool\gis_multi_site-master_multiple2\eRate_Routing.py", line 192, in rfpRoute
    arcpy.SelectLayerByAttribute_management('ident',"NEW_SELECTION",selection)
  File "c:\program files (x86)\arcgis\desktop10.6\arcpy\arcpy\management.py", line 7726, in SelectLayerByAttribute
    raise e
ExecuteError: ERROR 000358: Invalid expression
Failed to execute (SelectLayerByAttribute).

Failed to execute (eRateRFP).
Failed at Tue Sep 11 17:02:45 2018 (Elapsed Time: 8 minutes 22 seconds)
`

**Comment by RichThomasUniti** [comment]
For now, I renamed the layer as "FIBERCABLE" and herdcoded that name in the tool in 3 places. The long term solution is to reference the network dataset itself to determine what portions are existing fiber, rather than using a separate reference layer.
